name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - feat/josephine

jobs:
  build:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SECRET_KEY_DASHBOARD }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DASHBOARD }}/admindashboardjose/$GITHUB_SHA .
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DASHBOARD }}/admindashboardjose/$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy microservice-dashboard \
            --image asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DASHBOARD }}/admindashboardjose/$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GCP_REGION_DASHBOARD }} \
            --allow-unauthenticated \
